name: "Arduino CLI"
description: "Arduino CLI for Raspberry Pi"
version: "latest"
slug: "rpi-ardcli"
init: false
arch:
  - aarch64
#uart: true
full_access: true
homeassistant_api: true
devices:
  - /dev/ttyACM0
# services:
#   - mqtt:need
map:
  - addon_config:rw
image: "ghcr.io/linucks/rpi-ardcli"
