mqtt:
  host: core-mosquitto
  port: 1883
  user: addons
  password: Xi0nae7xeiboo8EiDeech9eing7zoathoh8eijoogoogeiz0Kaixef1reisha9oy
  topic_prefix: jens
  ha_discovery:
    enabled: yes

stream_modules:
  - name: dfrobot
    module: serial
    device: /dev/ttyACM0
    baud: 9600
    read_interval: 60

