    - name: Extract supervisor token
      ansible.builtin.command: cat /etc/profile.d/homeassistant.sh
      register: homeassistant_profile
    - name: Set supervisor token var
      set_fact:
        ha_supervisor_token: "{{ homeassistant_profile.stdout | regex_search('export SUPERVISOR_TOKEN=\"([a-f0-9]+)\"$', '\\1') | first }}"
      changed_when: false