- name: Add repository
  ansible.builtin.command: ha store add https://github.com/mattlongman/hassio-access-point

- name: Install add-on
  ansible.builtin.command: ha addons install 30e576d0_hassio-access-point

- name: Set Add-on options
  ansible.builtin.uri:
    url: http://supervisor/addons/30e576d0_hassio-access-point/options
    method: POST
    headers:
      Authorization: "BEARER {{ ha_supervisor_token }}"
    body: |
      { "options":
        {
        "ssid": "EWAPXX",
        "wpa_passphrase": "",
        "channel": "6",
        "address": "192.168.99.1",
        "netmask": "255.255.255.0",
        "broadcast": "192.168.99.255",
        "interface": "wlanXX",
        "hide_ssid": "0",
        "dhcp": "0",
        "dhcp_start_addr": "192.168.99.10",
        "dhcp_end_addr": "192.168.99.20",
        "allow_mac_addresses": [],
        "deny_mac_addresses": [],
        "debug": 0,
        "hostapd_config_override": [],
        "client_internet_access": "0",
        "client_dns_override": [],
        "dnsmasq_config_override": []
        }
      }
    body_format: json

