# Run with 
#ansible-playbook -i 100.101.225.134, ha.yml
# ---
- name: Setup Edible Wall Home Assistant
  hosts: all
  remote_user: fu
  become: true
  gather_facts: no
  tasks:
  - import_tasks: tasks/set_supervisor_token.yml
  - block:
    - import_tasks: tasks/setup_sensors.yml
    - import_tasks: tasks/setup_mqttio.yml
    - import_tasks: tasks/setup_configuration.yml
    environment:
      SUPERVISOR_TOKEN: "{{ ha_supervisor_token }}"