# Run with 
#ansible-playbook -i 100.101.225.134, ha.yml
# ---
- name: Setup Edible Wall Home Assistant
  hosts: all
  remote_user: fu
  become: true
  gather_facts: false
  tasks:
  - import_tasks: tasks/set_supervisor_token.yml
  - block:
    - import_tasks: tasks/setup_sensors.yml
    # - import_tasks: tasks/setup_mqttio.yml
    # - import_tasks: tasks/setup_tapo.yml
    # - import_tasks: tasks/setup_configuration.yml
    # - import_tasks: tasks/setup_ap.yml
    # - name: Restart HA
    #   ansible.builtin.command: ha core restart
    environment:
      SUPERVISOR_TOKEN: "{{ ha_supervisor_token }}"
